// src/components/input.svelte
<script lang="ts">
    import type { HTMLInputAttributes } from 'svelte/elements';

    interface $$Props extends HTMLInputAttributes {
        label: string;
    }

    let instance: HTMLInputElement;

    export let label: $$Props['label'];
    export let value = '';

    export function focus() {
        instance.focus();
    }
</script>

<label class="flex h-full w-full flex-col">
    <span>{label}</span>
    <input
        {...$$restProps}
        bind:value
        bind:this={instance}
        class="h-1/2 rounded border-[1px] border-solid border-light-border bg-transparent pl-2 text-sm dark:border-0 dark:bg-neutral-800 dark:placeholder-gray-300 dark:placeholder-opacity-60"
    />
</label>

// src/components/input/input.tsx
import { type ForwardedRef, type InputHTMLAttributes, forwardRef } from 'react';

type InputProps = InputHTMLAttributes<HTMLInputElement> & {
    label: string;
};

const InputComponent = (
    { label, ...props }: InputProps,
    ref: ForwardedRef<HTMLInputElement>,
): JSX.Element => (
    <label className="flex h-full w-full flex-col">
        <span>{label}</span>
        <input
            {...props}
            ref={ref}
            className="h-1/2 rounded border-[1px] border-solid border-light-border bg-transparent pl-2 text-sm dark:border-0  dark:bg-neutral-800 dark:placeholder-gray-300 dark:placeholder-opacity-60"
        />
    </label>
);

export const Input = forwardRef(InputComponent);
