// src/components/input.svelte
<script lang="ts">
    import type { HTMLInputAttributes } from 'svelte/elements';

    interface $$Props extends HTMLInputAttributes {
        label: string;
    }

    let instance: HTMLInputElement;

    export let label: $$Props['label'];
    export let value = '';

    export function focus() {
        instance.focus();
    }
</script>

<label class="flex h-full w-full flex-col">
    <span>{label}</span>
    <input
        {...$$restProps}
        bind:value
        bind:this={instance}
        class="h-1/2 rounded border-[1px] border-solid border-light-border bg-transparent pl-2 text-sm dark:border-0 dark:bg-neutral-800 dark:placeholder-gray-300 dark:placeholder-opacity-60"
    />
</label>

// components/input.tsx
import { InputHTMLAttributes } from 'react';

type InputProps = InputHTMLAttributes<HTMLInputElement>;

export const Input = (props: InputProps) => {
    return (
        <input
            {...props}
            className="pl-2 w-full h-full border-[1px] dark:border-0 border-solid bg-transparent dark:bg-neutral-800 rounded dark:placeholder-gray-300 dark:placeholder-opacity-50"
        />
    );
};
