// src/components/demo/nanostores/board/board.vue
<script setup lang="ts">
import { useStore } from '@nanostores/vue';

import * as cn from './board.css';
import { BOARD } from './constants';
import { $activeCell, isCellVisible } from './store';

const { offset } = defineProps<{ offset: number }>();

const cell = useStore($activeCell);
</script>

<template>
    <div :class="cn.container">
        <span :class="cn.title" style="color: #42b883">Vue</span>
        <div :class="cn.board">
            <div v-for="column in BOARD" :class="cn.column">
                <div v-for="[col, row] in column">
                    <div :class="cn.cell">
                        <svg
                            v-if="isCellVisible({ cell, col, offset, row })"
                            width="100%"
                            height="100%"
                        >
                            <circle fill="red" cy="50%" cx="50%" r="5" />
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// src/components/demo/nanostores/board/board.tsx
import { useStore } from '@nanostores/react';

import * as cn from './board.css';
import { BOARD } from './constants';
import { $activeCell, isCellVisible } from './store';

const Board = ({ offset }: { offset: number }) => {
    const cell = useStore($activeCell);

    return (
        <div className={cn.container}>
            <span className={cn.title} style={{ color: '#58C4DC' }}>
                React
            </span>
            <div className={cn.board}>
                {BOARD.map((column, index) => (
                    <div className={cn.column} key={column[index][0]}>
                        {column.map(([col, row]) => (
                            <div className={cn.cell} key={col + row}>
                                {isCellVisible({ cell, col, offset, row }) && (
                                    <svg width="100%" height="100%">
                                        <circle
                                            fill="red"
                                            cy="50%"
                                            cx="50%"
                                            r="5"
                                        />
                                    </svg>
                                )}
                            </div>
                        ))}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Board;
