// src/features/search-area/search-area.tsx
import { useRouter } from 'next/router';
import {
    type FormEventHandler,
    type MouseEventHandler,
    useCallback,
    useEffect,
    useRef,
    useState,
} from 'react';

import { Button } from '~components/button';
import { Input } from '~components/input';
import { Loader } from '~components/loader';
import { useKeypress } from '~hooks/use-keypress';

const QUERY_FIELD_NAME = 'q';

export const SearchArea = () => {
    const router = useRouter();
    const queryEl = useRef<HTMLInputElement>(null);
    const [query, setQuery] = useState('');
    const [loading, setLoading] = useState(false);

    const keyPressHandler = useCallback((e: KeyboardEvent) => {
        e.stopImmediatePropagation();
        queryEl.current?.focus();
    }, []);

    useEffect(() => {
        setLoading(false);

        const q = router.query[QUERY_FIELD_NAME]?.toString();

        if (q) {
            setQuery(q);
        }
    }, [router.asPath, router.query]);

    useKeypress('/', keyPressHandler);

    const onSubmit: FormEventHandler<HTMLFormElement> = (e) => {
        e.preventDefault();

        setLoading(true);

        const url = new URL(location.href);

        if (query) {
            url.searchParams.set(QUERY_FIELD_NAME, query);
        } else {
            url.searchParams.delete(QUERY_FIELD_NAME);
        }

        router.push(url);
    };

    const onClear: MouseEventHandler<HTMLButtonElement> = () => {
        setQuery('');

        const url = new URL(location.href);

        url.searchParams.delete(QUERY_FIELD_NAME);

        router.push(url);

        queryEl.current?.focus();
    };

    return (
        <form onSubmit={onSubmit} className="relative h-16 flex items-center">
            <Input
                label="Search notes"
                name={QUERY_FIELD_NAME}
                ref={queryEl}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                autoComplete="off"
                placeholder="Type here"
            />
            <div className="absolute right-0 bottom-0 h-1/2 flex gap-2 p-1">
                {query && (
                    <Button onClick={onClear} type="button">
                        Clear
                    </Button>
                )}
                <Button>Search</Button>
            </div>
            {loading && <Loader />}
        </form>
    );
};

// src/components/search-area.svelte
<script lang="ts">
    import { onDestroy, onMount } from 'svelte';

    import Button from '~components/button.svelte';
    import Input from '~components/input.svelte';
    import Loader from '~components/loader.svelte';
    import { QUERY_FIELD_NAME } from '~constants';

    interface $$Props {
        q: string;
    }

    export let q: $$Props['q'];

    let inputElement: any;
    let query = q;
    let loading = false;

    const keyPressHandler = (e: KeyboardEvent) => {
        if (e.key === '/') {
            e.stopImmediatePropagation();
            inputElement.focus();
        }
    };

    onMount(() => {
        typeof document !== 'undefined' &&
            document.addEventListener('keyup', keyPressHandler);
    });

    onDestroy(() => {
        typeof document !== 'undefined' &&
            document.removeEventListener('keyup', keyPressHandler);
    });

    const onSubmit = (e: SubmitEvent) => {
        e.preventDefault();

        loading = true;

        const url = new URL(location.href);

        if (query.length > 0) {
            url.searchParams.set(QUERY_FIELD_NAME, query);
        } else {
            url.searchParams.delete(QUERY_FIELD_NAME);
        }

        window.location.href = url.toString();
    };
</script>

<form on:submit={onSubmit} class="relative flex h-16 items-center">
    <Input
        bind:this={inputElement}
        bind:value={query}
        label="Search notes"
        name={QUERY_FIELD_NAME}
        autocomplete="off"
        placeholder="Type here"
    />
    <div class="absolute bottom-0 right-0 flex h-1/2 gap-2 p-1 text-sm">
        <Button>Search</Button>
    </div>
    {#if loading}
        <Loader />
    {/if}
</form>
